import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderComponent } from "./src/components/Header";
import AuthenticationProvider from "./src/contexts/Authentication/provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const response = await fetch(
        "https://61a1ef1b014e1900176de7d5.mockapi.io/api/v1/profile/1"
    );
    const data = await response.json();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthenticationProvider data={data}>
                    <HeaderComponent></HeaderComponent>
                    {children}
                </AuthenticationProvider>
            </body>
        </html>
    );
}
